namespace Engine
{
    /// <summary>
    /// map layers. Different items in the same square all live on the same layer.
    /// </summary>
    internal enum MapLayers
    {
        TERRAIN,
        FURNITURE,
        CREATURES,
        PLAYER,
        ITEMS,
    }
    /// <summary>
    /// for vertical roads
    /// </summary>
    internal enum RoadNames
    {
        Alder,
        Alm,
        Apple,
        Ash,
        Aspen,
        Birch,
        Baskins,
        Burk,
        Boston,
        Buston,
        Beaufort,
        Beligne,
        BellFlower,
        Cottonwood,
        Cypress,
        Chestnut,
        Cherry,
        Cedar,
        Chambers,
        Cormick,
        Dogwood,
        Danforth,
        Denmark,
        Dunn,
        Debutante,
        DawnView,
        Delaney,
        DuskView,
        England,
        Elders,
        Eagle,
        Edinburough,
        Echo,
        Esperoza,
        Elton,
        Elm,
        Fir,
        Franklin,
        Fredricks,
        Fabian,
        Fadler,
        Fey,
        Guittierez,
        Gabriel,
        Gomez,
        Gannon,
        Gorilla,
        Greensburg,
        Guthrow,
        Holly,
        Henderson,
        Haroldson,
        Hinkley,
        Hazelnut,
        Hogan,
        Hamburg,
        Hanson,
        Harris,
        Idlewine,
        Idriss,
        Ibex,
        Ibanez,
        Ipanema,
        Ihlenfeldt,
        Imbrogno,
        Juniper,
        Jasper,
        Jenkins,
        Jaxley,
        Jacobs,
        Jaillet,
        Jamal,
        Justice,
        Jackal,
        Kaczkowski,
        Kasimir,
        Kodak,
        Katz,
        Killinger,
        Kuiper,
        Klatski,
        Lark,
        Larimer,
        Lamilar,
        Lawrence,
        Luthor,
        Lamont,
        Lindbergh,
        Loxley,
        Lopez,
        LaPierre,
        MatrinLuthorKingJr,
        McMonohan,
        Montoya,
        Menendez,
        Miracle,
        Maze,
        Melon,
        Mayor,
        Martin,
        Norwood,
        Noddingham,
        Nigel,
        Neumann,
        Nathaniel,
        Oscar,
        Olive,
        Oak,
        Pear,
        Peach,
        Princeton,
        Quincy,
        Quebec,
        Quenton,
        Raspberry,
        Redman,
        Rodriguez,
        Spruce,
        Spear,
        Smith,
        Thompson,
        Taupe,
        Terweiliger,
        Utah,
        Ursula,
        Underbridge,
        VanStrom,
        Vanilla,
        VillaNova,
        Waterfront,
        Williams,
        Wapanaugh, 
        Xavier,
        Xanadu,
        Xylophone,
        YellowLine,
        Yew,
        Zedd,
        Zephraim,
        Zilch,       
    }

    /// <summary>
    /// for horizontal roads
    /// </summary>
    internal enum RoadNumbers
    {
        First,
        Second,
        Third,
        Fourth,
        Fifth,
        Sixth,
        Seventh,
        Eighth,
        Ninth,
        Tenth,
        Eleventh,
        Twelfth,
        Thirteenth,
        Fourteenth,
        Fifteenth,
        Sixteenth,
        Seventeenth,
        Eighteenth,
        Nineteenth,
        Twentieth,
        TwentyFirst,
        TwentySecond,
        TwentyThird,
        TwentyFourth,
        TwentyFifth,
        TwentySixth,
        TwentySeventh,
        TwentyEighth,
        TwentyNinth,
        Thirtieth,
        ThirtyFirst,
        ThirtySecond,
        ThirtyThird,
        ThirtyFourth,
        ThirtyFifth,
        ThirtySixth,
        ThirtySeventh,
        ThirtyEighth,
        ThirtyNinth,
        Fortieth,
        FortyFirst,
        FortySecond,
        FortyThird,
        FortyFourth,
        FortyFifth,
        FortySixth,
        FortySeventh,
        FortyEighth,
        FortyNinth,
        Fiftieth,
        FiftyFirst,
        FiftySecond,
        FiftyThird,
        FiftyFourth,
        FiftyFifth,
        FiftySixth,
        FiftySeventh,
        FiftyEighth,
        FiftyNinth,
        Sixtieth,
        SixtyFirst,
        SixtySecond,
        SixtyThird,
        SixtyFourth,
        SixtyFifth,
        SixtySixth,
        SixtySeventh,
        SixtyEighth,
        SixtyNinth,
        Seventieth,
        SeventyFirst,
        SeventySecond,
        SeventyThird,
        SeventyFourth,
        SeventyFifth,
        SeventySixth,
        SeventySeventh,
        SeventyEighth,
        SeventyNinth,
        Eightieth,
        EightyFirst,
        EightySecond,
        EightyThird,
        EightyFourth,
        EightyFifth,
        EightySixth,
        EightySeventh,
        EightyEighth,
        EightyNinth,
        Ninetieth,
        NinetyFirst,
        NinetySecond,
        NinetyThird,
        NinetyFourth,
        NinetyFifth,
        NinetySixth,
        NinetySeventh,
        NinetyEighth,
        NinetyNinth,
        OneHundred,
        OneHundredFirst,
    }
    /// <summary>
    /// Used for decorating structures
    /// </summary>
    internal enum RoomTypes
    {
        Parlor,
        Bedroom,
        MasterBedroom,
        Bathroom,
        Kitchen,
        DiningRoom,
        Yard,
        Closet
    }

    /// <summary>
    /// What type of structure are we building?
    /// </summary>
    internal enum StructureTypes
    {
        Testing,
        CentralPassageHouse,
        //CourtyardHouse,
        //Konak,
        //LogHouse,
        //HouseBarn,
        //SplitLevel,
        //UpperLusatian,
        //Cottage,
        //TrailerHome,
        //DuplixSemiDetached,
        //TriplexTripleDecker,
        //Quadplex,
        //Townhome,
        //DowntownShop,
        //DowntownOffice,
        //DowntownApartment,
        //Motel,
    }

    /// <summary>
    /// Bloodtype, useful for knowing donors and it's about the only thing you could test for in 1970
    /// </summary>
    internal enum BloodTypes
    {
        O,
        A,
        B,
        AB
    }

    /// <summary>
    /// currently unused, I think?
    /// </summary>
    internal enum MessageTypes
    {
        Warning,
        Status,
        Problem,
        Battle
    }

    /// <summary>
    /// The actions a player can take while playing
    /// </summary>
    internal enum GameActions
    {
        LookAtEverythingInSquare,
        LookAtPerson,
        Talk,
        TakePhotograph,
        GetItem,
        RemoveItemFromInventory,
        TogglePause,
        DustItemForPrints, //prints and tracks really just work the same way anyways
        ToggleNotes,
        ToggleInventory,
        ToggleMenu,
    }
}
